### PR TITLE
Increase the reliablity of the project, and provide help

### PR DESCRIPTION
**Pull request by dmssargent**
The repo did not initially run as to its defined behavior on my system when I got a correct setup ready. This is the improvements and additions I used to have the simulator working properly. V-REP seems quite happy to work with the code.  I turned some magic numbers into constants. 
## TODO
- [x] ~~The Android app now crashes :(, instead of not providing any feedback, if the IP address is invalid.~~
- [x] ~~The Interrupted Exceptions need to be properly handled.~~
- [x] ~~More work needs to be done with this to ensure that the Java client code works quite happily~~
- [x] ~~a logger needs to still be added~~
- [ ] adding more commenting.
- [ ] More Simulation Examples
## What I did
- I added a lot of error-handling code to the project.
- The port problem seems to be solved with this.
- I added a new Simulator OpMode (testing on the capabilities of V-REP)
- Refactored the motor to support an arbitrary number of motors

### CODE REVIEW

**Comment by dmssargent** [comment]
Do you want me to pull the GUI into this pull request?

**Comment by anoldguy** [comment]
In general, you should handle the merge conflicts in your branch. I'd do a `git fetch`; and then probably a `git merge master`. That should point out any merge conflicts you've got. Commit your solution to the conflicts, and push your merge + conflict resolution commits. That should take care of it.

**Comment by dmssargent** [comment]
I needed to push some local commits to GitHub. I added a logger to the code, and did some refactoring.

**Comment by HagertyRobotics** [comment]
Hi, we just saw your pull request and we are now a little confused.  This is our first time using github.  We just merged our gui branch into the master and made a few changes before we did that.  I guess we need to look through each of your patches and see if we can merge them into our new code.  Thanks so much for the help.

**Comment by dmssargent** [comment]
Just merge my code into its own branch, to provide a testing grounds (as I am not quite done, yet), if you want to handle it, and I will start merging back into the master branch. Then, you can merge the result into the master branch. I created the pull request a tad earlier than I should have. Sorry about that.

Do you me to play with the GUI in a separate request? 

Some GitHub guides: 
- https://guides.github.com/introduction/flow/index.html 
- https://rtfm.modx.com/community/contribute/using-git-and-github/

**Comment by dmssargent** [comment]
Oh dear me, the package layout seems to have changed, I **would _not_** recommend merging until I get my fork up-to-date with the changes, and everything situated. I don't see any usage of the xml writer library, am I correct?

**Comment by HagertyRobotics** [comment]
Ok we will wait until you get your fork up to date.  Sorry about that.  We didn't know anyone else was looking at the code.  We should have pushed our code earlier.  We used an xml reader on the Android to read the configuration from the PC.  On the PC we used JAXB but it was not available on the Android.   Thanks so much for your help.  We are trying to get a few sensors working because we have a summer camp next week for some new kids and it would be nice for them to start learning to code using the simulator.

**Comment by HagertyRobotics** [comment]
Oh, I think you were asking about the simplexml library.  Yes, we are not using that.  We tried it but couldn't get it to serialize our subclasses.

**Comment by HagertyRobotics** [comment]
Wow!  we are going to learn so much from looking at your changes.  We would also like to rename all of our packages from hagerty to org.ftccommunity.

**Comment by dmssargent** [comment]
Okay, you can start pushing my code into it's own branch, and test it to make sure you can use it before you merge into anything major.

**Comment by dmssargent** [comment]
I am refactoring the network communications to use just one TCP socket, instead of so many UDPs. Are you interested?

**Comment by HagertyRobotics** [comment]
Yes, that sounds great.  We wanted to have a thread for each controller.  How would you separate the packets from the phone?  Add a module number to the packet?

We are still testing your changes.  What was your thinking about the files in ftccommunity.  They were based on the older files but have stuff that could be added to the newer files.

**Comment by dmssargent** [comment]
I left the ftccommunity files there to leave behind a console application (for debugging purposes,) some of the files got changed a bit drastically when a updated the branch to the upstream version, so what I did in that may no longer apply. 

As to the packet separation, I am build still working the server, but I have a working mirror protocol (tested with fake data, the server sends a data, then I reply back with the same data with the server throws back to me.)  I am using Google Protobufs + Netty to use just a single port. Each data (I am calling a packet a data, since I am adding more info to the stream) gets throw in a FIFO queue buffer, that gets sorted and puts everything in LinkedLiskMultimap (Guava), that anything can access (and if the queue fills up, the software automatically removes the oldest packets), and if anything needs to clear their processing queue it can.

**Comment by HagertyRobotics** [comment]
Those packages look great.   I was thinking before of some kind of FIFO that you could access only the tagged packets you wanted.  

Will we still be able to have the separate debugging window that just shows the data?  I thought that it would be good to have the a different mode if you didn't want to start up the v-rep simulator and only wanted to see what was being sent.

**Comment by dmssargent** [comment]
Right now the following function signature is how something accesses its data that in the new system:

``` Java
public static byte[] getLatestData(@NotNull SimulatorData.Type.Types type) {...}
```

And I am using the following for debug output:

``` Java
for (byte test : data.getInfo(0).getBytes(StandardCharsets.US_ASCII)) {
            System.out.print(String.format("0x%02X ", test));
}
```

Right now, my first priority bug in this is that it may cause the WiFi to overheat, if left running for too long (the code does not respond to sleep, so I need to add sleep detection to throttle the server)

**Comment by dmssargent** [comment]
The WiFi overheating was because the wifi design on the device was bad, not the code which is code.
Though, I need to ask to you: do want me to include the TCP in this request?

**Comment by dmssargent** [comment]
Status update: I have the client side (in this case the computer) ready for testing. I don't have the server (Robot Controller) ready, though. I am using two ports: (7001 and 7002) both are required for now, but that can easily be changed (TCP 7001: main data socket; handles the majority of the server/client connection + a ping/pong heartbeat), (UDP 7002: a heartbeat command is sent from server using a multicast UDP socket that sends out a heartbeat packet containing how to connect to server: IP Address.) The code also complies in 16 seconds for me. Also, I am trying to get a ZTE Speed to use for this.

**Comment by HagertyRobotics** [comment]
I was finally able to merge in most of your changes.  I removed a few cosmetic changes from the main body of the FTC App to keep it clean.  Thank you for the help.

**Comment by HagertyRobotics** [comment]
I'll start looking at your new code.  I don't understand your question about including the TCP in the request?

**Comment by dmssargent** [comment]
Okay, I now know what to do about TCP, I will do another pull request about that when I am ready for it.

**Comment by HagertyRobotics** [comment]
I liked your networking approach.  The multicast will be nice so we don't have to program in the IP address each time.  Were you able to get a ZTE Speed?  I've been getting them at Wallmart.

**Comment by dmssargent** [comment]
I found a Moto E (close enough to a Moto G, to do) Our stores got wiped out of ZTE Speeds, and since it won't be used as a robot controller (I have yet to hear that our hardware has gotten ordered, but two weeks I know that we were getting ready to start the order the ZTEs and the controller, this takes about a month for us) Apparently, I need to add an alternative connection to the networking since the Moto (Lollipop 5.1) drops the current WiFi network to switch to Direct and we lose the signal, my code is modular enough that it can fail over to a bonded Bluetooth device (I read the about USB connections via Android, it can be done if I want to spend _time_ on it, but not fast)

**Comment by dmssargent** [comment]
I have figured out how to use a phone tether to run the simulator, I will add to the docs when I the pull request

**Pull request merged**
